# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-teamcity-messages.spec

# add or remove files that should be synced
files_to_sync:
  - python-teamcity-messages.spec
  - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: teamcity-messages
# downstream (Fedora) RPM package name
downstream_package_name: python-teamcity-messages

upstream_project_url: https://github.com/majamassarini/teamcity-messages

upstream_tag_template: v{version}

jobs:
- job: copr_build
  trigger: commit
  targets: 
  - fedora-stable
  - fedora-development
- job: propose_downstream
  trigger: release
  dist_git_branches:
  - fedora-stable
  - fedora-development
# downstream automation:
- job: koji_build
  trigger: commit
  allowed_pr_authors: ["packit"]
  dist_git_branches:
  - fedora-stable
  - fedora-development
- job: bodhi_update
  trigger: commit
  dist_git_branches:
    - fedora-stable # branched version, rawhide updates are created automatically
