# See the documentation for more information:
# https://packit.dev/docs/configuration/

packit_instances: [ "stg"]

specfile_path: python-teamcity-messages.spec

files_to_sync:
    - python-teamcity-messages.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: teamcity-messages
# downstream (Fedora) RPM package name
downstream_package_name: python-teamcity-messages

upstream_project_url: https://github.com/majamassarini/teamcity-messages

upstream_tag_template: v{version}

notifications:
  failure_comment:
    message: "One of the tests failed for {commit_sha}. @admin check logs {logs_url}, packit dashboard {packit_dashboard_url} and external service dashboard {external_dashboard_url}"

jobs:
  - job: copr_build
    trigger: pull_request
    targets: 
      - fedora-rawhide
