# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-teamcity-messages.spec

# add or remove files that should be synced
files_to_sync:
    - python-teamcity-messages.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: teamcity-messages
# downstream (Fedora) RPM package name
downstream_package_name: python-teamcity-messages

upstream_project_url: https://github.com/majamassarini/teamcity-messages
issue_repository: https://github.com/majamassarini/teamcity-messages
copy_upstream_release_description: true

upstream_tag_template: v{version}

jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-development

  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches:
        - fedora-development

#  - job: koji_build
#    trigger: commit
#    metadata:
#      dist_git_branches:
#        - fedora-development
#
#  - job: bodhi_update
#    trigger: commit
#    metadata:
#      dist_git_branches:
#        - fedora-development

#jobs:
#- job: copr_build
#  trigger: commit
#  metadata:
#    targets: fedora-stable
